### ISSUE TITLE
울산 지역 버스 정류장 조회불가

### ISSUE THREAD

**Issue by LeunoP** [gunyu1019/TrafficApplication#4]
![Screenshot_20220904_112906_eamemu](https://user-images.githubusercontent.com/110764037/188294497-c0f43df7-4b09-404c-bd9e-c0e19c1c30db.png)
![Screenshot_20220904_112857_eamemu](https://user-images.githubusercontent.com/110764037/188294500-c3d2b5d0-65f2-4e41-bcf5-d1f8c51e4cf9.png)
#
수도권은 정상적으로 로드가 되는데 울산 지역은 현재 조회가 안되네요
울산쪽 위치기반은 뜨는데 정류장 검색으로 검색하면 안뜨는것도있네요

**Comment by gunyu1019** [comment]
버그를 제보해주셔서 감사합니다. 빠른 시일 내에 원인을 조사한 뒤, 해결 방법을 마련해오도록 하겠습니다. 불편을 드려 죄송합니다. :(

**Comment by gunyu1019** [comment]
원인 조사 결과는 다음과 같습니다.

1. [trafficAPI](https://github.com/gunyu1019/trafficAPI)에서 울산광역시 버스 도착 정보를 요청 할 경우 [] (empty Array)를 반환함.
2. `openapi.its.ulsan.kr` 에서 서비스 연결 거부(ERR_CONNECTION_REFUSED)가 발생함.

따라서, 이번 이슈는 버스 애플리케이션 문제가 아니며, 관련 기관(울산광역시)에 [API 오류 신고](https://www.data.go.kr/bbs/qna/selectQna.do?pageIndex=1&bbsId=QNA_0000000000037591&searchCondition2=&cndCtgryPortal=&cndCtgryApi=&bindCndCtgry=&searchCondition6=&sort-post=CND_ALL&searchKeyword1=)를 등록한 상태입니다.
빠른 시일 내에 해결할 수 있도록 대체API를 찾는 등의 조치하도록 하겠습니다.

**Comment by LeunoP** [comment]
확인 감사합니다

**Comment by LeunoP** [comment]
![Screenshot_20230208_105603_Google Play Store](https://user-images.githubusercontent.com/110764037/217419832-4e7665d4-cfe6-4ebe-b286-3889ab0a4360.png)
성불 하셔도 될거 같습니다...
